[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where    = ["src"]
exclude  = ["tests*"]

[project]
name = "CC_CuMC"
version = "0.0.1"
description = "GPU-native (ish - compiled using Numba in Python) forward-integration and monte-carlo analysis of ODE systems."
authors = [
    { name="Chris Cameron" }
]
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "numpy",
    "numba",
    "numba-cuda",
    "cupy-cuda12x",
    "scipy",
]
[project.urls]
Homepage = "https://github.com/ccam80/smc.git"
Issues = "https://github.com/https://github.com/ccam80/smc/issues"

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests"
]
markers = [
    "nocudasim: Will fail if run on the GPU simulator, only test on real GPU"
]
addopts = [
    "--import-mode=importlib",
    "-ra"
]
filterwarnings = [
    "ignore::numba.core.errors.NumbaPerformanceWarning",
]
