# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Nightly to TestPyPI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *" 
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    name: Build Distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          
      - name: Set build timestamp
        run: echo "BUILD_TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      
      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Rename built artifacts with timestamp
        run: |
          for f in dist/*; do
            base=$(basename "$f")
            if [[ "$base" == *.tar.gz ]]; then
              name="${base%.tar.gz}"
              ext=".tar.gz"
            else
              name="${base%.*}"
              ext=".${base##*.}"
            fi
            mv "$f" "dist/${name}-${BUILD_TIMESTAMP}${ext}"
          done
      
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

   
  test-pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    # Dedicated environments with protections for publishing are strongly recommended.
    # For more information, see: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-protection-rules
    environment:
      name: testpypi
      url: https://test.pypi.org/p/cubie
      
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          repository-url: https://test.pypi.org/legacy/
          verbose: true
